// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badgeStack': string;
  'loggedUserInfoContainer': string;
  'nameAndBadgesContainer': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
