// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centerNavigationContainer': string;
  'fiubaLogo': string;
  'leftNavigationContainer': string;
  'loggedUserInfo': string;
  'logoTitle': string;
  'menuTab': string;
  'navigationContainer': string;
  'rightNavigationContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
