// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookingButton': string;
  'bookingContainer': string;
  'iconWithText': string;
  'imageContainer': string;
  'serviceImage': string;
  'serviceNameAndDescriptionContainer': string;
  'tagsContainer': string;
  'tagsIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
