// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fiubaIcon': string;
  'form': string;
  'formContainer': string;
  'formTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
